name: onboarding_2
description: A Flutter project with onboarding screens, localization, and theming.
publish_to: "none" # المشروع محلي

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Widgets & State Management
  provider: ^6.0.5

  # Navigation (اختياري)
  go_router: ^14.2.0

  # ✅ Smooth Page Indicator
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Localization
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
